services:
  jupyterhub:
    image: jupyterhub_img
    build: ./docker_build
    ports:
      - 8150:8000
    volumes:
      - ./data/home:/home
      - ./data/exchange:/srv/nbgrader/exchange
    # entrypoint: ["/srv/jupyterhub/entrypoint.sh"]
